/*
 * Copyright (c) 2021 Chipsea Technologies (Shenzhen) Corp., Ltd. All rights reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#ifndef _BT_COMMON_ERROR_H
#define _BT_COMMON_ERROR_H

enum bt_common_error
{
    BT_NO_ERROR   = 0x00,
    BT_UNKNOWN_COMMAND = 0x01,
    BT_UNKNOWN_ID = 0x02,
    BT_HARDWARE_FAILURE = 0x03,
    BT_PAGE_TIMEOUT = 0x04,
    BT_AUTH_FAILURE = 0x05,
    BT_PIN_MISSING = 0x06,
    BT_MEMORY_CAPA_EXCEED = 0x07,
    BT_CON_TIMEOUT = 0x08,
    BT_CON_LIMIT_EXCEED = 0x09,
    BT_SYNC_CON_LIMIT_DEV_EXCEED = 0x0A,
    BT_CON_ALREADY_EXISTS = 0x0B,
    BT_COMMAND_DISALLOWED = 0x0C,
    BT_CONN_REJ_LIMITED_RESOURCES = 0x0D,
    BT_CONN_REJ_SECURITY_REASONS = 0x0E,
    BT_CONN_REJ_UNACCEPTABLE_BDADDR = 0x0F,
    BT_CONN_ACCEPT_TIMEOUT_EXCEED = 0x10,
    BT_UNSUPPORTED = 0x11,
    BT_INVALID_HCI_PARAM = 0x12,
    BT_REMOTE_USER_TERM_CON = 0x13,
    BT_REMOTE_DEV_TERM_LOW_RESOURCES = 0x14,
    BT_REMOTE_DEV_POWER_OFF = 0x15,
    BT_CON_TERM_BY_LOCAL_HOST = 0x16,
    BT_REPEATED_ATTEMPTS = 0x17,
    BT_PAIRING_NOT_ALLOWED = 0x18,
    BT_UNKNOWN_LMP_PDU = 0x19,
    BT_UNSUPPORTED_REMOTE_FEATURE = 0x1A,
    BT_SCO_OFFSET_REJECTED = 0x1B,
    BT_SCO_INTERVAL_REJECTED = 0x1C,
    BT_SCO_AIR_MODE_REJECTED = 0x1D,
    BT_INVALID_LMP_PARAM = 0x1E,
    BT_UNSPECIFIED_ERROR = 0x1F,
    BT_UNSUPPORTED_LMP_PARAM_VALUE = 0x20,
    BT_ROLE_CHANGE_NOT_ALLOWED = 0x21,
    BT_LMP_RSP_TIMEOUT = 0x22,
    BT_LMP_COLLISION = 0x23,
    BT_LMP_PDU_NOT_ALLOWED = 0x24,
    BT_ENC_MODE_NOT_ACCEPT = 0x25,
    BT_LINK_KEY_CANT_CHANGE = 0x26,
    BT_QOS_NOT_SUPPORTED = 0x27,
    BT_INSTANT_PASSED = 0x28,
    BT_PAIRING_WITH_UNIT_KEY_NOT_SUP = 0x29,
    BT_DIFF_TRANSACTION_COLLISION = 0x2A,
    BT_QOS_UNACCEPTABLE_PARAM = 0x2C,
    BT_QOS_REJECTED = 0x2D,
    BT_CHANNEL_CLASS_NOT_SUP = 0x2E,
    BT_INSUFFICIENT_SECURITY = 0x2F,
    BT_PARAM_OUT_OF_MAND_RANGE = 0x30,
    BT_ROLE_SWITCH_PEND = 0x32,
    BT_RESERVED_SLOT_VIOLATION = 0x34,
    BT_ROLE_SWITCH_FAIL = 0x35,
    BT_EIR_TOO_LARGE = 0x36,
    BT_SP_NOT_SUPPORTED_HOST = 0x37,
    BT_HOST_BUSY_PAIRING = 0x38,
    BT_CONTROLLER_BUSY = 0x3A,
    BT_UNACCEPTABLE_CONN_PARAM = 0x3B,
    BT_ADV_TO = 0x3C,
    BT_TERMINATED_MIC_FAILURE = 0x3D,
    BT_CONN_FAILED_TO_BE_EST = 0x3E,
    BT_CCA_REJ_USE_CLOCK_DRAG = 0x40,
    BT_TYPE0_SUBMAP_NOT_DEFINED = 0x41,
    BT_UNKNOWN_ADVERTISING_ID = 0x42,
    BT_LIMIT_REACHED = 0x43,
    BT_OPERATION_CANCELED_BY_HOST = 0x44,

    BT_HW_UART_OUT_OF_SYNC = 0x00,
    BT_HW_MEM_ALLOC_FAIL = 0x01,
};

#endif // _BT_COMMON_ERROR_H
